feedforward/chat/urls.py
from django.urls import path 

from . import views

app_name = 'chat'

urlpatterns = [
    path('<int:pk>/', views.detail, name="detail"),
    path('', views.inbox, name="inbox"),
    path('new/<int:item_pk>/', views.new_chat, name="new"),
]

feedforward/feedforward/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include

from core.views import index, contact, about
urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('chat.urls')),
    path('about/', about, name='about'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedforward/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

feedforward/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=256)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    
    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    description = models.TextField(blank = True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default =False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    weight = models.FloatField()
    city = models.CharField(max_length=50)
        
    def __str__(self):
        return self.name

class Review(models.Model):
    user = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)



class ReviewMessage(models.Model):
    review = models.ForeignKey(Review, related_name='rev_messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_reviews', on_delete=models.CASCADE)

feedforward/item/forms.py
from django import forms

from .models import Item, ReviewMessage

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price','weight', 'city', 'image', )
        widgets = {
            'category': forms.Select(attrs= {
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs= {
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'weight': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'city': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs= {
                'class': INPUT_CLASSES
            })

            
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold', 'weight',)
        widgets = {
            'name': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs= {
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs= {
                'class': INPUT_CLASSES
            }),
            'weight': forms.TextInput(attrs= {
            'class': INPUT_CLASSES
            })
        }

class ReviewMessageForm(forms.ModelForm):
    class Meta:
        model = ReviewMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

feedforward/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import NewItemForm, EditItemForm, ReviewMessageForm
from .models import Item, Category, Review, ReviewMessage
from chat.models import Chat
from chat.forms import ChatMessage, ChatMessageForm 

def browse(request):
    query=request.GET.get('query','')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    item = Item.objects.filter(is_sold=False)

    if category_id:
        item = item.filter(category_id=category_id)

    if query: 
        item = item.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/browse.html', {
        'items': item,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })




def detail(request, pk,):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    review = Review.objects.filter(user=item.created_by).first()

    if request.method == "POST":
        form = ReviewMessageForm(request.POST)

        if form.is_valid():
            review_message = form.save(commit=False)

            # Check if a valid Review instance exists
            if review:
                review_message.review = review
                review_message.created_by = request.user
                review_message.save()

                # Optionally, update the review instance (if needed)
                review.save()

                return redirect('item:detail', pk=pk)
            else:
                return redirect('item:detail', pk=pk)
    else:
        form = ReviewMessageForm()

    return render(request, 'item/detail.html', {
        'review': review,
        'form': form,
        'item': item,
        'related_items': related_items,
    })

@login_required
def new(request):

    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')



@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })

feedforward/item/templates/item/browse.html
{% extends 'core/base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}
    <div class="p-6 grid grid-cols-4 gap-4 rounded-xl" style="background:#eee1cf;">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Find bananas, bananas or bananas...">
                <button class="mt-2 py-4 px-8 text-lb bg-green-500 hover:bg-green-700 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <div class="grid grid-cols-1 gap-4 h-auto justify-self-end justify-items-end my-3">
                {% for category in categories %}
                <div class="w-full h-full" >
                    <a href="{% url 'item:browse' %}?query={{query}}&category={{category.id}}">
                    <button class='w-full h-auto transition ease-out hover:-translate-y-1 hover:scale-110'>
    
                        <div class="p-3 rounded-xl flex gap-5 " style="background:#fcf5eb; {% if category.id == category_id %} background:#cfc9c0; {% endif %}">
                            <p class='text-xl'> {{category.name}}</p>
                            <p class='text-gray-400'>{{category.items.count}} items</p>
                        </div>
                    </button>
                    </a>
                </div>
    
                {% endfor %}
            </div>

            <hr class="my-6">
            <p class="font-semibold">Clear filters</p>
 
            <a href="{% url 'item:browse' %}">
                <button class="mt-2 py-4 px-8 text-lb bg-red-500 text-white rounded-xl hover:bg-red-700">Clear</button>
            </a>
         

        </div>

        <div class="col-span-3  p-6">
            <div class="grid gap-y-20 gap-x-0 grid-cols-3 h-auto w-full ">
                {% for item in items %}
                    <div class="w-4/5 h-90 ">
                        <a href="{% url 'item:detail' item.id %}">
                            <button class='w-auto h-90 transition ease-out hover:-translate-y-1 hover:scale-110 '>
                       
                            <div>
                                <img src="{{item.image.url}}" class='rounded-t-xl object-cover h-80 w-96'> 
                            </div>
    
                            <div class='p-6 rounded-b-xl' style="background:#fcf5eb;">
                                <h2 class='text-2xl'> {{item.name}}</h2>
                                <p class='text-gray-400'> Price: {{item.price}}</p>
                            </div>
                        </button>
                        </a>
                    </div>
                {% endfor %}
            </div>  
        </div>
    </div>
{% endblock %}

feedforward/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="flex gap-6">

            <img src="{{ item.image.url }}" class="object-cover h-90 w-96 rounded-xl">
    

        <div class="p-6 w-full rounded-xl" style="background:#eee1cf;">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong> {{ item.price }}</p>
            <p class="text-gray-500"><strong>Donator: </strong> {{ item.created_by.username }}</p>
            <p class="text-gray-500"><strong>Weight: </strong> {{ item.weight }}</p>
            <p class="text-gray-500"><strong>City: </strong> {{ item.city }}</p>

            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">
                        Description
                    </strong><br>
                    {{ item.description }}
                </p>
            {% endif %}

            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 rounded-xl" style="background:#fcf5eb;">
                    <p>This is your listing!</p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Edit Listing</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete Listing</a>
                </div>
            {% else %}
                <a href="{% url "chat:new" item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Contact donator</a>
            {% endif %}
        </div>
    </div>

    <div class="mt-6 mb-6 px-6 py-12 rounded-xl flex flex-wrap-reverse" style="background:#eee1cf;"> 
        <h2 class="mb-12 text-3xl font-semibold text-center order-3 w-full">Related listings</h2>
        <div class="grid gap-y-20 gap-x-0 grid-cols-3 h-auto w-2/3 order-1">
            {% for item in related_items %}
                <div class="w-4/5 h-90 ">
                    <a href="{% url 'item:detail' item.id %}">
                        <button class='w-auto h-90 transition ease-out hover:-translate-y-1 hover:scale-110 '>
                 
                        <div>
                            <img src="{{item.image.url}}" class='rounded-t-xl object-cover h-80 w-96'> 
                        </div>

                        <div class='p-6 rounded-b-xl' style="background:#fcf5eb;">
                            <h2 class='text-2xl'> {{item.name}}</h2>
                            <p class='text-gray-400'> Price: {{item.price}}</p>
                        </div>
                    </button>
                    </a>
                </div>
            {% endfor %}
        </div> 
    </div>
    
    <h1 class="mb-6 text-3xl">Donator Reviews</h1>

    <div class="space-y-6">
        {% for message in review.rev_messages.all %}
            <div class="p-6 flex bg-green-300 rounded-xl" style="{% if message.created_by != request.user %}background:#eee1cf;{% endif %}"> 
                <div>
                    <p class="mb-4"><strong>{{message.created_by.username}}</strong> | {{message.created_at}}</p>
                    <p>{{ message.content }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <form method="POST" action="." class="mt-6">
        {% csrf_token %}

        {{form.as_p}}
        <button class="mt-6 py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Send</button>
    </form>
{% endblock %}

feedforward/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Submit</button>
    </form>
{% endblock %}  