feedforward/chat/urls.py
from django.urls import path 

from . import views

app_name = 'chat'

urlpatterns = [
    path('<int:pk>/', views.detail, name="detail"),
    path('', views.inbox, name="inbox"),
    path('new/<int:item_pk>/', views.new_chat, name="new"),
]

feedforward/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

feedforward/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

feedforward/feedforward/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include

from core.views import index, contact, about
urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('inbox/', include('chat.urls')),
    path('about/', about, name='about'),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedforward/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

feedforward/core/models.py
from django.db import models

# Create your models here.

feedforward/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
        username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your username',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your password',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))

class SignupForm(UserCreationForm):
        class Meta:
                model = User
                fields = ('username', 'email', 'password1', 'password2')

        username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your username',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))
        
        email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'example@mail.com',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))
        
        password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your password',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))
        
        password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password',
                                                                 'class': 'w-full py-4 px-6 rounded-xl'}))

feedforward/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from django.contrib.auth import logout
from .forms import SignupForm
from django.contrib.auth.decorators import login_required
from item.models import Review
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories' : categories,
        'items' : items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

@user_passes_test(lambda u: u.is_anonymous)
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()
            review = Review.objects.create(user = user)
            review.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form':form
    })

@login_required
def logout_view(request):
    logout(request)
    return redirect('core:index')

feedforward/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}Welcome {%endblock%}

{% block content %}
<!-- <h1 class="text-4xl  px-60 py-10 font-bold">About us</h1> --> 

<div class="w-auto h-auto  px-60 py-5 flex justify-between space-x-6 border-b border--200 rounded-xl" style="background:#eee1cf;">
    <div class="space-y-3 mt-6">
        <h2 class="text-[40px] font-bold ">Our Vision</h2>
        <p class="text-lg">At FeedForward, we envision a world where no one goes to bed hungry, and where surplus food is seen as an opportunity to make a positive impact in the lives of others. We are committed to creating a sustainable and efficient solution to food waste, one meal at a time. Our belief extends beyond merely providing nourishment; it's about fostering community, promoting dignity, and addressing the root causes of hunger. By transforming surplus food into a lifeline for those in need, we aim to build a future where compassion and collaboration pave the way for a hunger-free world. </p>
    </div>
    <img src="https://i.imgur.com/OBYvkmT.png" class="h-96 w-80 rounded-xl">
</div>

<div class="w-auto h-auto py-10 px-60 py-5 flex justify-between space-x-6 ">
    <img src="https://i.imgur.com/5MbQCz2.png" class="h-96 w-80 rounded-xl">
    <div class="space-y-3 mt-6">
        <h2 class="text-[40px] font-bold ">What we do</h2>
        <p class="text-lg">Our platform connects food donors, whether they are restaurants, grocery stores, or individuals, with local charities and community organizations. By leveraging technology, we streamline the process of food donation and distribution, ensuring that perfectly good food doesn't end up in landfills but instead reaches the plates of those who need it the most.</p>
    </div>
    
</div>

<div class="w-auto h-auto py-10 px-60 py-5 flex justify-between space-x-6 border-b border--200 rounded-xl" style="background:#eee1cf;">
    <div class="space-y-3 mt-6">
        <h2 class="text-[40px] font-bold ">Our Vision</h2>
        <p class="text-lg">At FeedForward, we envision a world where no one goes to bed hungry, and where surplus food is seen as an opportunity to make a positive impact in the lives of others. We are committed to creating a sustainable and efficient solution to food waste, one meal at a time. Our belief extends beyond merely providing nourishment; it's about fostering community, promoting dignity, and addressing the root causes of hunger. By transforming surplus food into a lifeline for those in need, we aim to build a future where compassion and collaboration pave the way for a hunger-free world. </p>
    </div>
    <img src="https://i.imgur.com/OBYvkmT.png" class="h-96 w-80 rounded-xl">
</div>

<div class="w-auto h-auto py-10 px-60 py-5 flex justify-between space-x-6 ">
    <img src="https://i.imgur.com/5MbQCz2.png" class="h-96 w-80 rounded-xl">
    <div class="space-y-3 mt-6">
        <h2 class="text-[40px] font-bold ">What we do</h2>
        <p class="text-lg">Our platform connects food donors, whether they are restaurants, grocery stores, or individuals, with local charities and community organizations. By leveraging technology, we streamline the process of food donation and distribution, ensuring that perfectly good food doesn't end up in landfills but instead reaches the plates of those who need it the most.</p>
    </div>
    
</div>
{% endblock %}

feedforward/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css" rel="stylesheet" />

        <title>{% block title %}{%endblock%} | FeedForward</title>
    </head>
    
    <body style="background:#fcf5eb;">
        <nav class = "px-6 py-6 h-20  flex justify-between items-center border-b border-gray-200 mt-6 ml-6 mr-6 rounded-xl" style="background:#eee1cf;" >
            
                <a href="{%url 'core:index'%}">
                    <img src="https://i.imgur.com/ZPNDavg.png" class="h-20 hover:brightness-75 max-w-50">
                </a>
    

       

                <div class = "space-x-6">
                    <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500"> New Item </a>
                    <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-gray-500"> Browse </a>

                    {% if request.user.is_authenticated %}
                        <a href="{% url "chat:inbox" %}">
                            <button class="px-6 py-2.5 transition ease-out shadow hover:shadow-lg  text-lg font-semibold bg-gradient-to-r from-green-500 text-white rounded-xl to-green-700 hover:-translate-y-1 hover:scale-110 hover:from-green-600 hover:to-green-800 duration-150 ">Inbox</button>
                        </a>
                        <a href="{% url 'dashboard:index' %}">
                            <button class="px-6 py-2.5 transition ease-out shadow hover:shadow-lg text-lg font-semibold bg-gradient-to-r from-gray-500 text-white rounded-xl to-gray-700 hover:-translate-y-1 hover:scale-110 hover:from-gray-600 hover:to-gray-800 duration-150">Dashboard</button>
                        </a>
                    {% else %}
                        <a href="{% url 'core:signup' %}">
                            <button class="px-6 py-2.5 transition ease-out shadow hover:shadow-lg  text-lg font-semibold bg-gradient-to-r from-green-500 text-white rounded-xl to-green-700 hover:-translate-y-1 hover:scale-110 hover:from-green-600 hover:to-green-800 duration-150 ">Sign Up</button>
                        </a>
                        <a href="{% url 'core:login' %}">
                            <button class="px-6 py-2.5 transition ease-out shadow hover:shadow-lg text-lg font-semibold bg-gradient-to-r from-gray-500 text-white rounded-xl to-gray-700 hover:-translate-y-1 hover:scale-110 hover:from-gray-600 hover:to-gray-800 duration-150">Log In</button>
                        </a>
                    {% endif %}
                </div>

    
            
        </nav>
            
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 mb-6 ml-6 mr-6 flex justify-between bg-gray-800 rounded-xl" style="background:#eee1cf;">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-green-700">About</h3>
                
                <p class="text-lg text-gray-500">About us section</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-green-700">Menu</h3>
                
                <ul class="space-y-2">
                    <li><a href="{%url 'about'%}" class="text-lg text-green-500 hover:text-green-700">About</a></li>
                    <li><a href="{%url 'core:contact'%}" class="text-lg text-green-500 hover:text-green-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-green-500 hover:text-green-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-green-500 hover:text-green-700">Terms of use</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{%url 'core:logout'%}" class="text-lg text-green-500 hover:text-green-700">Log Out</a></li>
                    {% endif %}
                </ul>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>
    </body>
</html>

feedforward/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{%endblock%}

{% block content %}
<h1>The contact page</h1>
{% endblock %}

feedforward/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <h2 class="text-4xl mb-6 text-center font-semibold">Discover affordable food near you!</h2>
    <form method="get" action="{% url 'item:browse' %}" class="flex justify-center">

        <input name="query" class="w-1/3 justify-end py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Find bananas, bananas or bananas...">

        <button class="ml-6 py-4 px-8 text-lb bg-green-500 hover:bg-green-700 text-white rounded-xl">Search</button>

    </form>
    {% if not request.user.is_authenticated %}
    <a href="{% url 'core:signup' %}">
        <h2 class=" my-6 text-center hover:underline font-semibold">Want to donate? Create an account.</h2>
    </a>
    {% endif %}

    <div class="mt-6 mb-6 px-6 py-12 rounded-xl flex flex-wrap-reverse" style="background:#eee1cf;"> 
        <h2 class="mb-12 text-3xl font-semibold text-center order-3 w-full">Newest Listings</h2>
    
        <div class="grid gap-y-20 gap-x-0 grid-cols-4 h-auto w-full ">
            {% for item in items %}
                <div class="w-4/5 h-90 ">
                    <a href="{% url 'item:detail' item.id %}">
                        <button class='w-auto h-90 transition ease-out hover:-translate-y-1 hover:scale-110 '>
                    
                        <div>
                            <img src="{{item.image.url}}" class='rounded-t-xl object-cover h-80 w-96'> 
                        </div>

                        <div class='p-6 rounded-b-xl' style="background:#fcf5eb;">
                            <h2 class='text-2xl'> {{item.name}}</h2>
                            <p class='text-gray-400'> Price: {{item.price}}</p>
                        </div>
                    </button>
                    </a>
                </div>
            {% endfor %}
        </div>    
    </div>

{% endblock %}

feedforward/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 rounded-xl" style="background:#eee1cf;">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

feedforward/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 rounded-xl" style="background:#eee1cf;">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}